# -*- coding: utf-8 -*-
"""processing image data for Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvDdGopAqj7aUT_dgSBkA21pil0ppvVw
"""

# getting an image using get

!wget 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVoRAgoSaskueF09GeTvwO3cll4Rj0w0BARA368ZXU6bGqCK_19KvdCd0&s=10'

# importing the image module from matplotlib library

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

# loading an image through matplotlib.image module

img = mpimg.imread('/content/dog.jpg')

type(img)

print(img.shape)

print(img)

# displaying the image from numpy array

img_plot = plt.imshow(img)
plt.show()

from PIL import Image

img = Image.open('/content/dog.jpg')
img_resized = img.resize((200, 200))

img_resized.save('dog_Image_resized.jpg')

# displaying the image from numpy array

img_res = mpimg.imread('/content/dog_Image_resized.jpg')
img_res_plot = plt.imshow(img)
plt.show()

print(img_res.shape)

# importing OpenCV library
import cv2

img = cv2.imread('/content/dog.jpg')

type(img)

img.shape

grayscale_image = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

type(grayscale_image)

grayscale_image.shape

from google.colab.patches import cv2_imshow

# displaying the image
cv2_imshow(grayscale_image)

# saving the grayscale image
cv2.imwrite('dog_grayscale.jpg', grayscale_image)